var pc,index=0,dict,firefox=void 0!=window.mozRTCPeerConnection;navigator.getUserMedia=navigator.mozGetUserMedia||navigator.webkitGetUserMedia;navigator.getUserMedia({audio:!0,video:!0},onUserMediaSuccess,onUserMediaError);
function onUserMediaSuccess(a){var b=document.getElementById("localVideo");b.src=URL.createObjectURL(a);b.style.display="block";pc=new (window.RTCPeerConnection||window.mozRTCPeerConnection||window.webkitRTCPeerConnection)({iceServers:[{urls:"stun:stun.l.google.com:19302"},{urls:"stun:stun.services.mozilla.com"}]});pc.addStream(a);pc.onicecandidate=function(a){pc.localDescription&&prepareEmail()};pc.onaddstream=function(a){document.getElementById("remoteVideo").src=URL.createObjectURL(a.stream)};
""==location.search?pc.createOffer(onDescCreated,onCreateOfferError):processPeerData(location.search.substr(1));document.getElementsByTagName("input")[0].onchange=function(){this.checked?pc.addStream(a):pc.removeStream(a);b.style.display=this.checked?"block":"none"}}function onUserMediaError(a){console.log("User media error: "+JSON.stringify(a))}function onCreateOfferError(a){logError("Error creating offer: "+JSON.stringify(a))}
function onDescCreated(a){pc.setLocalDescription(a,onLocalDescSuccess,onLocalDescError)}function onLocalDescSuccess(){prepareEmail()}function onLocalDescError(a){logError("Local description could not be created: "+JSON.stringify(a))}
function prepareEmail(){var a=document.getElementsByTagName("a")[0];if("complete"==pc.iceGatheringState&&""==a.textContent){dict="udp ;typ ;tcp ;host ;srflx ;raddr ;rport ;tcptype ;active ".split(";");var b=Array(34);b[0]=strBetween("o=","\r\n");b[5]=strBetween("a=group:BUNDLE "," ");index--;b[6]=strBetween(" ","\r\n");b[2]=strBetween("m=audio "," ");addToDict(b[2]);b[3]=strBetween("SAVPF ","\r");b[4]=strBetween("c=IN IP4 ","\r");addToDict(b[4]);for(var c=20;26>c&&(b[c]=nextIceCandidate(),"a=candidate:"==
pc.localDescription.sdp.substr(index,12));c++);b[1]=strBetween("msid:"," ");index--;b[12]=strBetween(" ","\r");index=0;b[10]=strBetween("a=ssrc:"," ");b[11]=strBetween("cname:","\r").replace(/\//g,".");b[13]=strBetween("m=video "," ");b[14]=strBetween("SAVPF ","\r");for(c=26;32>c&&(b[c]=nextIceCandidate(),"a=candidate:"==pc.localDescription.sdp.substr(index,12));c++);b[16]=strBetween("a=ssrc:"," ");b[17]=strBetween("msid:"+b[1]+" ","\r");index=0;b[9]=strBetween("a=fingerprint:sha-256 ","\r").replace(/:/g,
"");index=0;b[7]=strBetween("a=ice-ufrag:","\r").replace(/\//g,".").replace(/;/g,"_");index=0;b[8]=strBetween("a=ice-pwd:","\r").replace(/\//g,".").replace(/;/g,"_");b[19]=pc.localDescription.type.charAt(0);b=b.join("~");for(c=0;c<dict.length;c++)var d="*"+String.fromCharCode(c+(26>c?65:97)),e=new RegExp(dict[c].replace(/\./g,"\\."),"g"),b=b.replace(e,d);b="?"+(dict.slice(9).join("~")+"*"+b).replace(/\s/g,"+")+"%0D%0A%0D%0A";c="&body=Please click the link below to connect with me. Note: Chrome must be your default browser.%0D%0A%0D%0A"+
location.hostname+location.pathname;""==location.search?(a.textContent="Send email inviting someone to talk",a.href="mailto:?subject=Can we talk%3F"+c+b,a.onclick="window.open("+a.href+", 'mail'); event.preventDefault()",window.addEventListener("storage",function(a){processPeerData(a.newValue);localStorage.clear()})):(a.textContent="Send email accepting invitation to talk",a.href="mailto:?subject=Yes, we can talk"+c+"answer.htm"+b,a.onclick=setupDone)}}
function addToDict(a){0>dict.indexOf(a)&&2<a.length&&0<pc.localDescription.sdp.indexOf(a,index)&&dict.push(a)}function nextIceCandidate(){for(var a=strBetween("a=candidate:","\r\n").replace("generation 0",""),b=a.split(" "),c=0;c<b.length;c++)addToDict(b[c]+" ");return a}function strBetween(a,b){var c=pc.localDescription.sdp,d=c.indexOf(a,index);if(0>d)return"";var d=d+a.length,e=c.indexOf(b,d);index=e+b.length;return c.substring(d,e)}
function processPeerData(a){var b=new (window.RTCSessionDescription||window.mozRTCSessionDescription||window.webkitRTCSessionDescription),c=a.indexOf("*"),d=("udp+~typ+~tcp+~host+~srflx+~raddr+~rport+~tcptype+~active+~"+a.substring(0,c)).split("~");a=a.substr(c+1);for(c=0;c<d.length;c++){var e=new RegExp("\\*"+String.fromCharCode(c+(26>c?65:97)),"g");a=a.replace(e,d[c])}a=a.split("~");c=0>a[0].indexOf("mozilla");b.sdp="v=0\r\no="+a[0].replace(/\+/g," ")+"\r\ns=-\r\nt=0 0\r\na=group:BUNDLE "+a[5]+
" "+a[6]+lines("audio",a)+"a=sendrecv\r\na=rtcp-mux"+audioCodecs(c)+ssrcLines(a[1],a[12],a[10],a[11])+lines("video",a)+"a=sendrecv\r\na=rtcp-mux"+videoCodecs(c)+ssrcLines(a[1],a[17],a[16],a[11])+"\r\n";b.type="o"==a[19]?"offer":"answer";pc.setRemoteDescription(b,onRemoteDescSuccess,onRemoteDescError)}function ssrcLines(a,b,c,d){return"\r\na=msid:"+a+" "+b+"\r\na=ssrc:"+c+" cname:"+d.replace(/\./g,"/")}
function lines(a,b){for(var c="audio"==a?20:26,d="",e=c;e<c+6&&""!=b[e]&&void 0!==b[e];e++)d+="\r\na=candidate:"+b[e];return"\r\nm="+a+" "+b["audio"==a?2:13]+" RTP/SAVPF "+b["audio"==a?3:14].replace(/\+/g," ")+"\r\nc=IN IP4 "+b[4]+d.replace(/\+/g," ")+"\r\na=ice-ufrag:"+b[7].replace(/\./g,"/").replace(/_/g,";")+"\r\na=ice-pwd:"+b[8].replace(/\./g,"/").replace(/_/g,";")+"\r\na=fingerprint:sha-256 "+b[9].replace(/(.{2})/g,"$1:").slice(0,-1)+"\r\na=setup:"+("o"==b[19]?"actpass":"active")+"\r\na=mid:"+
b["audio"==a?5:6]+"\r\n"}function audioCodecs(a){return a?"\r\na=rtpmap:111 opus/48000/2\r\na=fmtp:111 minptime=10; useinbandfec=1\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:106 CN/32000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:126 telephone-event/8000\r\na=maxptime:60":"\r\na=rtpmap:109 opus/48000/2\r\na=rtpmap:9 G722/8000/1\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000"}
function videoCodecs(a){return a?"\r\na=rtpmap:100 VP8/90000\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=rtcp-fb:100 goog-remb\r\na=rtpmap:116 red/90000\r\na=rtpmap:117 ulpfec/90000\r\na=rtpmap:96 rtx/90000\r\na=fmtp:96 apt=100":"\r\na=rtcp-fb:120 nack\r\na=rtcp-fb:120 nack pli\r\na=rtcp-fb:120 ccm fir\r\na=rtcp-fb:126 nack\r\na=rtcp-fb:126 nack pli\r\na=rtcp-fb:126 ccm fir\r\na=rtcp-fb:97 nack\r\na=rtcp-fb:97 nack pli\r\na=rtcp-fb:97 ccm fir\r\na=rtcp-mux\r\na=rtpmap:120 VP8/90000\r\na=rtpmap:126 H264/90000\r\na=rtpmap:97 H264/90000"}
function onRemoteDescSuccess(){console.log("Remote sdp successfully set");"offer"==pc.remoteDescription.type?pc.createAnswer(onDescCreated,onCreateAnswerError):setupDone()}function onRemoteDescError(a){logError("Remote sdp could not be set: "+(a.message?a.message:a))}function onCreateAnswerError(a){logError("Error creating answer: "+(a.message?a.message:a))}
function setupDone(){document.getElementsByTagName("a")[0].style.display="none";document.getElementById("remoteVideo").style.display="block";document.getElementsByTagName("label")[0].style.display="block";console.log("Connected")}function logError(a){console.log(a)}function gotoFullScreen(a){a.requestFullscreen=a.mozRequestFullScreen||a.webkitRequestFullscreen;a.requestFullscreen()};